[package]
name = "left-truncatable-primes"
version = "0.1.0"
authors = ["Rhahi <like.a.hina@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ramp = "0.6.0"